### PR TITLE
Spatialautocorr marine -- to be verified

### PR DESCRIPTION
**Pull request by Marine-th**

### CODE REVIEW

**Comment by MarieEtienne** [comment]
You have merged a section which does not pass the checks ! I will have to revert your merge commit. 
Could you specify which package you are using ?

**Comment by MarieEtienne** [comment]
Could you please open a new PR and verify that all checks are passed before the merge. If you need additionnal package, I can install them
@ascheubel @Marine-th

**Comment by Marine-th** [comment]
Ah yes sorry, i clicked the button by mistake before the checks were finished. 
I am not sure about the others in my team, but I would need the packages "spdep", spatialreg" and "gwrr"

**Comment by ascheubel** [comment]
I also need the package ade4, thanks!

**Pull request merged**
